# Tab bar at the top, browser-style
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round

# Slightly nicer font
font_size 12.0

# Make new tabs open in same directory
map ctrl+shift+t new_tab_with_cwd

# Remap to familiar copy/paste
map ctrl+v paste_from_clipboard

# nerd font
font_family JetBrainsMono Nerd Font
font_size 12.0

# start it where you want
